### PR TITLE
Fix import in header for RN48 compatibility.

### PR DESCRIPTION
**Pull request by ssomnoremac**
Simple change in import. Tested on 48.2

### CODE REVIEW

**Comment by ssomnoremac** [comment]
did not test in earlier versions. Might break.

**Comment by ssomnoremac** [comment]
@markrickert, @SudoPlz I have updated the PR but have yet to test. I am not a contributor so I cannot merge. also @luisfuertes @himrocks33 @cwagner22

**Comment by xwenliang** [comment]
Thanks for all of you. I'll publish a new version in a second.

**Comment by markrickert** [comment]
Awesome. Thanks everyone! I'll close my identical PR :)

**Pull request merged**
