### PR TITLE
Add Feature: customizing wheel width and flex

### PR DESCRIPTION
**Pull request by dqisme**
Make wheels can be set a specific width or flex on `iOS` or `Android` platform.

On `iOS` platform, wheels will be rendered by a specific number or regarded as `auto` case(equal division) in other types. If the length of `wheelWidth` array is less than the pickerData's, the unspecific width will be regarded as auto case *(i.e. as much wide as possible)*.

On `Android` platform, variable devices have so many different screen resolution that we can not give a specific point number to all of them. So wheels will be rendered with width weight which is something like `flex` in `react-native`. All you need to do is giving a proportion to each wheel of `pickerData`. If the length of `wheelFlex` array is less than the pickerData's, the unspecific wheel will be regarded as `0` weight *(i.e. will not display)*.

### CODE REVIEW

**Comment by hejiaji** [comment]
@shexiaoheng @xwenliang 你们看看可否把这个PR merge了？很有用

**Comment by shexiaoheng** [comment]
稍等，我先看下

**Comment by shexiaoheng** [comment]
测试了下，当前提的PR有bug，Android端当wheelFlex的长度比pickerData的长度小的时候，比如wheelFlex为2，pickerData为3，则只显示2列数值。iOS端貌似不通过...   然后两个平台的名字应该保持统一

**Comment by shexiaoheng** [comment]
这个我们自己加吧，非常感谢 @dqisme 。: )

**Comment by xwenliang** [comment]
we have supported this feature on `v4.0.6`, thanks all of you

**Pull request closed without merging**
